## Working through whatever



In [218]:
using Revise

In [219]:
includet("Fractals.jl")

In [220]:
using .Fractals

In [221]:
?iterateFunction

search: iterateFunction



This is the iterate function that takes a compelx function and iterates it a certain number of times.

returns a vector of complex numbers for each iteration including the initial


In [222]:
f(x) = x^2 + im

iterateFunction(f, 0 + 0im, 10)

11-element Vector{Complex}:
  0 + 0im
  0 + 1im
 -1 + 1im
  0 - 1im
 -1 + 1im
  0 - 1im
 -1 + 1im
  0 - 1im
 -1 + 1im
  0 - 1im
 -1 + 1im

In [223]:
leavingNumber()

LoadError: MethodError: no method matching leavingNumber()
Closest candidates are:
  leavingNumber(::Complex) at C:\Users\xfouc\OneDrive\Documents\Mandelbrot-\Fractals.jl:96
  leavingNumber(::Complex, ::Complex) at C:\Users\xfouc\OneDrive\Documents\Mandelbrot-\Fractals.jl:96
  leavingNumber(::Complex, ::Complex, ::Integer) at C:\Users\xfouc\OneDrive\Documents\Mandelbrot-\Fractals.jl:96

In [224]:
leavingNumber(1+1im)

3

In [225]:
leavingNumber(0+0im, 0)

LoadError: MethodError: no method matching leavingNumber(::Complex{Int64}, ::Int64)
Closest candidates are:
  leavingNumber(::Complex) at C:\Users\xfouc\OneDrive\Documents\Mandelbrot-\Fractals.jl:96
  leavingNumber(::Complex, ::Complex) at C:\Users\xfouc\OneDrive\Documents\Mandelbrot-\Fractals.jl:96
  leavingNumber(::Complex, ::Complex, ::Integer) at C:\Users\xfouc\OneDrive\Documents\Mandelbrot-\Fractals.jl:96

In [226]:
inMandelbrot(0+0im)

LoadError: MethodError: no method matching leavingNumber(::Complex{Int64}, ::Int64)
Closest candidates are:
  leavingNumber(::Complex) at C:\Users\xfouc\OneDrive\Documents\Mandelbrot-\Fractals.jl:96
  leavingNumber(::Complex, ::Complex) at C:\Users\xfouc\OneDrive\Documents\Mandelbrot-\Fractals.jl:96
  leavingNumber(::Complex, ::Complex, ::Integer) at C:\Users\xfouc\OneDrive\Documents\Mandelbrot-\Fractals.jl:96

In [227]:
inMandelbrot(1+1im)

LoadError: MethodError: no method matching leavingNumber(::Complex{Int64}, ::Int64)
Closest candidates are:
  leavingNumber(::Complex) at C:\Users\xfouc\OneDrive\Documents\Mandelbrot-\Fractals.jl:96
  leavingNumber(::Complex, ::Complex) at C:\Users\xfouc\OneDrive\Documents\Mandelbrot-\Fractals.jl:96
  leavingNumber(::Complex, ::Complex, ::Integer) at C:\Users\xfouc\OneDrive\Documents\Mandelbrot-\Fractals.jl:96

In [228]:
inMandelbrot(1+1im, -100)

LoadError: ArgumentError: The maximum number of iterations must be positive

In [229]:
include("Fractals-Test.jl")

Constructor Test FractalView: Error During Test at C:\Users\xfouc\OneDrive\Documents\Mandelbrot-\Fractals-Test.jl:7
  Test threw exception
  Expression: FractalView(0im, 1im) isa FractalView
  ArgumentError: The mininum complex number must be smaller than the maximun
  Stacktrace:
   [1] FractalView(min::Complex{Int64}, max::Complex{Int64})
     @ Main.Fractals C:\Users\xfouc\OneDrive\Documents\Mandelbrot-\Fractals.jl:17
   [2] macro expansion
     @ C:\Users\xfouc\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Test\src\Test.jl:464 [inlined]
   [3] macro expansion
     @ C:\Users\xfouc\OneDrive\Documents\Mandelbrot-\Fractals-Test.jl:7 [inlined]
   [4] macro expansion
     @ C:\Users\xfouc\AppData\Local\Programs\Julia-1.8.0\share\julia\stdlib\v1.8\Test\src\Test.jl:1357 [inlined]
   [5] top-level scope
     @ C:\Users\xfouc\OneDrive\Documents\Mandelbrot-\Fractals-Test.jl:6
Constructor Test FractalView: Error During Test at C:\Users\xfouc\OneDrive\Documents\Mandelbrot-\Fractal

LoadError: LoadError: Some tests did not pass: 3 passed, 0 failed, 2 errored, 0 broken.
in expression starting at C:\Users\xfouc\OneDrive\Documents\Mandelbrot-\Fractals-Test.jl:4

In [230]:
FractalView()

FractalView(0 + 0im, 2 + 2im, 800, 600)

In [231]:
FractalView(0+im, 5+5im)

FractalView(0 + 1im, 5 + 5im, 800, 600)

In [232]:
FractalView(0+0im, 5+5im, 1000, 800)

FractalView(0 + 0im, 5 + 5im, 1000, 800)

In [233]:
FractalView(0im, 1im, -123, 100)

LoadError: ArgumentError: The mininum complex number must be smaller than the maximun

In [234]:
FractalView(0im,1im,0, 100)

LoadError: ArgumentError: The mininum complex number must be smaller than the maximun

In [235]:
FractalView(0im,1im,123, 0)

LoadError: ArgumentError: The mininum complex number must be smaller than the maximun

In [236]:
f(x) = x^2

iterateFunction(f, 0im, 5)

6-element Vector{Complex}:
 0 + 0im
 0 + 0im
 0 + 0im
 0 + 0im
 0 + 0im
 0 + 0im

In [237]:
iterateFunction(f, -1im, 5)

6-element Vector{Complex}:
  0 - 1im
 -1 + 0im
  1 + 0im
  1 + 0im
  1 + 0im
  1 + 0im

In [238]:
iterateFunction(f, -.5+.5im, 5)

6-element Vector{Complex}:
             -0.5 + 0.5im
              0.0 - 0.5im
            -0.25 - 0.0im
           0.0625 + 0.0im
       0.00390625 + 0.0im
 1.52587890625e-5 + 0.0im

In [239]:
leavingNumber(-1im) # stays
leavingNumber(-1.01im) # leaves
leavingNumber(.4+0im) # leaves
leavingNumber(-.5+.5im) # stays
leavingNumber(2im) # already left 

2

In [240]:
fractal = FractalView(-2-2im, 2+2im, 5,5)

FractalView(-2 - 2im, 2 + 2im, 5, 5)

In [241]:
mandelbrotViewer(fractal)

In [242]:
xVector = LinRange(real(fractal.min), real(fractal.max), fractal.width)

5-element LinRange{Float64, Int64}:
 -2.0,-1.0,0.0,1.0,2.0

In [243]:
yVector = reverse(collect(LinRange(imag(fractal.min), imag(fractal.max), fractal.height)))

5-element Vector{Float64}:
  2.0
  1.0
  0.0
 -1.0
 -2.0

In [244]:
    m = zeros(Complex,  fractal.height, fractal.width)

    xVector = LinRange(real(fractal.min), real(fractal.max), fractal.width)
    yVector = reverse(LinRange(imag(fractal.min), imag(fractal.max), fractal.height))

for x in 1:fractal.width
    for y in 1:fractal.height
            print("(", xVector[x],", " ,yVector[y], "im), ")
            m[y,x] = complex(xVector[x], yVector[y])#xVector[x] + yVector[y]
        end
    end

    m

(-2.0, 2.0im), (-2.0, 1.0im), (-2.0, 0.0im), (-2.0, -1.0im), (-2.0, -2.0im), (-1.0, 2.0im), (-1.0, 1.0im), (-1.0, 0.0im), (-1.0, -1.0im), (-1.0, -2.0im), (0.0, 2.0im), (0.0, 1.0im), (0.0, 0.0im), (0.0, -1.0im), (0.0, -2.0im), (1.0, 2.0im), (1.0, 1.0im), (1.0, 0.0im), (1.0, -1.0im), (1.0, -2.0im), (2.0, 2.0im), (2.0, 1.0im), (2.0, 0.0im), (2.0, -1.0im), (2.0, -2.0im), 

5×5 Matrix{Complex}:
 -2.0+2.0im  -1.0+2.0im  0.0+2.0im  1.0+2.0im  2.0+2.0im
 -2.0+1.0im  -1.0+1.0im  0.0+1.0im  1.0+1.0im  2.0+1.0im
 -2.0+0.0im  -1.0+0.0im  0.0+0.0im  1.0+0.0im  2.0+0.0im
 -2.0-1.0im  -1.0-1.0im  0.0-1.0im  1.0-1.0im  2.0-1.0im
 -2.0-2.0im  -1.0-2.0im  0.0-2.0im  1.0-2.0im  2.0-2.0im

In [245]:
mand = FractalView(-2-2im, 2+2im, 500,400)

FractalView(-2 - 2im, 2 + 2im, 500, 400)

In [246]:
mandelbrotViewer(mand)